DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE AAU.Visit
ADD COLUMN `VisitBeginDate` DATETIME NULL AFTER `Day`,
ADD COLUMN `VisitEndDate` DATETIME NULL AFTER `Day`;
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	