DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE AAU.StreetTreatCase 
  ADD UNIQUE INDEX PatientId_UNIQUE (PatientId);
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	