DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
	ALTER TABLE AAU.Patient
	DROP COLUMN Comment;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	