service: apoms
runtime: nodejs12
env: standard

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /
  static_files: apoms/index.html
  upload: apoms/index.html

- url: /
  static_dir: apoms