service: apoms-staging
runtime: nodejs12
env: standard

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /(.*)
  secure: always
  redirect_http_response_code: 301
  static_files: apoms/index.html
  upload: apoms/index.html
  static_dir: apoms
