DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
  
ALTER TABLE AAU.EmergencyCase 
ADD COLUMN `Comments` VARCHAR(650) NULL DEFAULT NULL AFTER `SameAsEmergencyCaseId`;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	