CREATE TABLE AAU.streattreatcase (
  `StreatTreatCaseId` INT NOT NULL AUTO_INCREMENT,
  `PriorityId` INT NULL,
  `StatusId` INT NULL,
  `TeamId` INT NULL,
  `MainProblemId` INT NULL,
  `AdminComments` TEXT NULL,
  `OperatorNotes` TEXT NULL,
  `ClosedDate` DATE NULL,
  `EarlyReleaseFlag` TINYINT(1) NULL,
  `IsDeleted` TINYINT(1) NULL DEFAULT  0,
  `PatientId` INT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedDate` DATETIME NULL,
  PRIMARY KEY (`StreatTreatCaseId`));