DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
    
	ALTER TABLE `AAU`.`User` ADD COLUMN `FixedDayOff` TINYINT NOT NULL AFTER `DateTimeOffsetHours`;
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;
