DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
  
  ALTER TABLE `AAU`.`Problem` DROP INDEX `IX_Problem_UNIQUE`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DELIMITER //

CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`AnimalType` DROP INDEX `IX_AnimalType_UNIQUE`;


END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`CallOutcome` DROP INDEX `IX_CallOutcome_UNIQUE`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`EmergencyCode` DROP INDEX `IX_EmergencyCode_UNIQUE`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`PatientStatus` DROP INDEX `IX_PatientStatus_UNIQUE`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`CallType` DROP INDEX `IX_CallType_UNIQUE`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`SurgerySite` DROP INDEX `IX_SurgerySite_UNIQUE`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`SurgeryType` DROP INDEX `IX_SurgeryType_UNIQUE`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`PatientCallerInteractionOutcome` DROP INDEX `IX_PatientCallerInteractionOutcome_UNIQUE`;
ALTER TABLE `AAU`.`PatientCallerInteractionOutcome` 
CHANGE COLUMN `PatientCallOutcomeId` `PatientCallerInteractionOutcomeId` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `PatientCallOutcome` `PatientCallerInteractionOutcome` VARCHAR(64) NULL DEFAULT NULL ;


END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`MainProblem` DROP INDEX `IX_MainProblem_UNIQUE`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`TreatmentArea` DROP INDEX `IX_TreatmentArea_UNIQUE`;
ALTER TABLE `AAU`.`TreatmentArea` 
CHANGE COLUMN `AreaId` `TreatmentAreaId` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `Area` `TreatmentArea` VARCHAR(100) NOT NULL ,
CHANGE COLUMN `SortArea` `SortOrder` INT(11) NULL DEFAULT NULL ;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;


ALTER TABLE `AAU`.`TreatmentArea` ADD UNIQUE INDEX `IX_TreatmentArea_UNIQUE` (`TreatmentArea` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`MainProblem` ADD UNIQUE INDEX `IX_MainProblem_UNIQUE` (`MainProblem` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`PatientCallerInteractionOutcome` ADD UNIQUE INDEX `IX_PatientCallerInteractionOutcome_UNIQUE` (`PatientCallerInteractionOutcome` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`SurgeryType` ADD UNIQUE INDEX `IX_SurgeryType_UNIQUE` (`SurgeryType` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`SurgerySite` ADD UNIQUE INDEX `IX_SurgerySite_UNIQUE` (`SurgerySite` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`CallType` ADD UNIQUE INDEX `IX_CallType_UNIQUE` (`CallType` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`PatientStatus` ADD UNIQUE INDEX `IX_PatientStatus_UNIQUE` (`PatientStatus` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`EmergencyCode` ADD UNIQUE INDEX `IX_EmergencyCode_UNIQUE` (`EmergencyCode` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`CallOutcome` ADD UNIQUE INDEX `IX_CallOutcome_UNIQUE` (`CallOutcome` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`AnimalType` ADD UNIQUE INDEX `IX_AnimalType_UNIQUE` (`AnimalType` ASC, `OrganisationId` ASC) INVISIBLE;
ALTER TABLE `AAU`.`Problem` ADD UNIQUE INDEX `IX_Problem_UNIQUE` (`Problem` ASC, `OrganisationId` ASC) INVISIBLE;

