DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
	ALTER TABLE AAU.EmergencyCode
	ADD COLUMN SortOrder INT NULL AFTER EmergencyCode;
	
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;
