DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
	ALTER TABLE AAU.SurgeryType
	ADD COLUMN SortOrder INT NULL AFTER ExpectedDuration;	
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

