DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
	ALTER TABLE AAU.AnimalType CHANGE COLUMN Sort SortOrder INT;
	
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;
