DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
	ALTER TABLE AAU.PatientCallerInteractionOutcome
	ADD COLUMN SortOrder INT NULL AFTER PatientCallOutcome;
	
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

