DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
  ALTER TABLE `aau`.`team` 
  CHANGE COLUMN `IsDeleted` `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0 ;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	