DROP TABLE IF EXISTS AAU.ReleaseDetails; 
CREATE TABLE AAU.ReleaseDetails (
  `ReleaseDetailsId` int NOT NULL AUTO_INCREMENT,
  `OrganisationId` int NOT NULL,
  `PatientId` int NOT NULL,
  `RequestedUser` varchar(45) NOT NULL,
  `RequestedDate` date NOT NULL,
  `ReleaseTypeId` int NOT NULL,
  `CallerId` int NOT NULL,
  `ComplainerNotes` varchar(450) DEFAULT NULL,
  `ComplainerInformed` tinyint DEFAULT NULL,
  `Releaser1Id` int DEFAULT NULL,
  `Releaser2Id` int DEFAULT NULL,
  `PickupDate` date DEFAULT NULL,
  `BeginDate` date DEFAULT NULL,
  `EndDate` date DEFAULT NULL,
  `CreatedDate` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ReleaseDetailsId`),
  UNIQUE KEY `Release⁯Id_UNIQUE` (`ReleaseDetailsId`),
  KEY `FK_ReleaseDetailsOrganisationId_OrganisationOrganisationId_idx` (`OrganisationId`),
  KEY `FK_ReleaseDetailsPatientId_PatientPatientId_idx` (`PatientId`),
  KEY `FK_ReleaseDetailsReleaser1Id_UserUserId_idx` (`Releaser1Id`,`Releaser2Id`),
  KEY `FK_ReleaseReleaser2Id_UserUserId_idx` (`Releaser2Id`),
  CONSTRAINT `FK_ReleaseOrganisationId_OrganisationOrganisationId` FOREIGN KEY (`OrganisationId`) REFERENCES AAU.Organisation (`OrganisationId`),
  CONSTRAINT `FK_ReleasePatientId_PatientPatientId` FOREIGN KEY (`PatientId`) REFERENCES AAU.Patient (`PatientId`),
  CONSTRAINT `FK_ReleaseReleaser1Id_UserUserId` FOREIGN KEY (`Releaser1Id`) REFERENCES AAU.User (`UserId`),
  CONSTRAINT `FK_ReleaseReleaser2Id_UserUserId` FOREIGN KEY (`Releaser2Id`) REFERENCES AAU.User (`UserId`)
);
