DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE AAU.StreetTreatCase 
ADD COLUMN `AssignedAmbulanceId` INT NULL AFTER `OrganisationId`,
ADD COLUMN `AmbulanceAssignmentTime` DATETIME NULL AFTER `AssignedAmbulanceId`;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	