DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE AAU.ReleaseDetails 
ADD COLUMN `IsStreetTreatRelease` TINYINT NULL DEFAULT 0 AFTER `AmbulanceAssignmentTime`;
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	