DELIMITER ;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `AAU`.`User` ADD COLUMN `DateTimeOffsetHours` VARCHAR(10) NOT NULL DEFAULT '+05:30' AFTER `PermissionArray`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

