DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `AAU`.`Treatment` 
ADD COLUMN `UpdateTime` DATETIME NULL AFTER `Comment`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	