DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `AAU`.`User` 
ADD COLUMN `Preferences` JSON NULL AFTER `PermissionArray`;

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	