DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
	ALTER TABLE AAU.Patient CHANGE COLUMN Position GUID VARCHAR(128);
	UPDATE AAU.Patient SET GUID = UUID();

  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;




