

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE AAU.Organisation ADD TimeZoneOffset VARCHAR(10) AFTER SocketEndPoint;

UPDATE AAU.Organisation SET TimeZoneOffset = '+5:30';

  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;
