DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE AAU.OrganisationMetaData ADD VehicleDefaults JSON;
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;
