DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
	ALTER TABLE AAU.SurgerySite
	ADD COLUMN SortOrder INT NULL AFTER Longitude;	
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;