DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE `AAU`.`EmergencyCase` 
ADD COLUMN `SelfAdmission` TINYINT NULL;


END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	
