DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
	ALTER TABLE AAU.Problem
	ADD COLUMN SortOrder INT NULL AFTER Problem;
	
  
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;