DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
 ALTER TABLE AAU.Patient
ADD COLUMN `Age` INTEGER;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	