DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
  ALTER TABLE `aau`.`patient` 
  ADD COLUMN `PatinetOutcomeId` INT NULL DEFAULT NULL AFTER `KnownAsName`
  ADD COLUMN `SameAsNumber` INT NULL DEFAULT NULL AFTER `PatinetOutcomeId`;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	