DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE AAU.Team ADD COLUMN `TeamColour` VARCHAR(45) NULL DEFAULT NULL ;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;	